### ISSUE TITLE
GTK+ 2.x and GTK+ 3 conflict

### ISSUE THREAD

**Issue by pwyq** [christoskokas/mini_project_kokas#1]
Hello @christoskokas , I am building this repo in a fresh Ubuntu 20.04 environment. I encounter the following error when I try to run `orbslam3`.

> (ORB-SLAM3: Current Frame:47234): Gtk-ERROR **: 15:36:02.869: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

What I have tried:
- I installed OpenCV from source and built with the GTK2 option

I am not sure where does the conflict come from other than OpenCV. It would be much appreciated if you may help on this issue.

**Comment by christoskokas** [comment]
It seems that ORB-SLAM3 uses both GTK+ 2.x and GTK+ 3 which is not supported. Are you use you when opencv was installed you added the option `-D WITH_GTK_2_X=ON`? In the coming days i will reinstall this repo on a fresh environment and the readme steps will be updated and hopefully this error will be resolved!

**Comment by pwyq** [comment]
Thank you for the fast reply.
Yes, I'm sure I added that option through cmake-gui. I will try again with command line cmake.

**Comment by pwyq** [comment]
Using your suggestion, I think the error is gone.

Before `cmake`, we need to switch to the 4.2.0 version of OpenCV
```
git checkout 4.2.0
```
Then I used the following cmake command.
```
cmake -D CMAKE_BUILD_TYPE=RELEASE \ -D CMAKE_INSTALL_PREFIX=/usr/local \ -D INSTALL_C_EXAMPLES=ON \ -D INSTALL_PYTHON_EXAMPLES=ON \    -D OPENCV_GENERATE_PKGCONFIG=ON \ -D OPENCV_EXTRA_MODULES_PATH=~/opencv_build/opencv_contrib/modules \ -D BUILD_EXAMPLES=ON -D WITH_GTK_2_X=ON ..
```
